// <auto-generated />
namespace DO_AN_1_TEST01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addSanPhamAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSanPhamAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202005310630130_addSanPhamAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
